---
name: Quarto Publish

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/quarto@3b5a73012982bdeb04d02bcf81cc28bdfe5d4ee5 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          requirements-txt: ${{ github.workspace }}/requirements.txt